### ISSUE TITLE
make the extension more integrated with the system

### ISSUE THREAD

**Issue by allaeddineomc** [avanishsubbiah/material-you-theme#10]
make the extension decide weather it's dark or light based on the settings instead of a toggle it will give much better integration with the system and fix the integration with that extension that sets dark mode automatically at night , also make it that the extension detects when the wallpaper changes and updates the theme without the need for pressing a button , this will make it much more pleasant to use and will eliminate the need for having a menu on the top bar .

**Comment by avanishsubbiah** [comment]
Commit 931f43e removes the duplicate dark mode toggle from the extension popup menu, and instead it reads what the user has set for their system dark theme preference. I haven't tested if this makes it compatible with Night Theme Switcher, but I think it should now.

I haven't been able to get it to recognize when the background has been set yet. This code 
```
const settings = new Gio.Settings({ schema: 'org.gnome.desktop.background' });
settings.connect('changed::picture-uri', () => { log('Default background changed!'); });
settings.connect('changed::picture-uri-dark', () => { log('Dark background changed!'); });
```
should do it, but for some reason changing the background doesn't trigger the `changed::picture-uri` hook

**Comment by avanishsubbiah** [comment]
Commit 293e316 makes the extension check for wallpaper updates to automatically regenerate theme when the user changes the wallpaper, and commit b0cff5e removes the indicator after fixing extension cleanup after disable().

The extension works now without any manual input. I will be adding a settings panel later to allow for user configuration in the style of [Rounded Window Corners](https://github.com/yilozt/rounded-window-corners)
