### ISSUE TITLE
Pale contrast with ver.8 for dark theme

### ISSUE THREAD

**Issue by darkblaze69** [avanishsubbiah/material-you-theme#19]
Version 7 was perfect with colors, but probably light theme was low contrast.
But now with version 8 dark theme has low contrast for colors, but light theme looks good.
V7 perfect for dark theme:
![mat-u-v7-1](https://user-images.githubusercontent.com/6976920/182770074-d5902d7a-e715-40cb-a947-8030a1da75f2.png)
![mat-u-v7-2](https://user-images.githubusercontent.com/6976920/182770077-73144c3d-767e-426c-83e4-69fb5d24548d.png)

V8 pale contrast for dark theme:
![mat-u-v8-1](https://user-images.githubusercontent.com/6976920/182770065-b46f7052-894f-4694-9ab0-c9dcc117d550.png)
![mat-u-v8-2](https://user-images.githubusercontent.com/6976920/182770072-7995fd49-2413-4a1a-aa74-a4e3d580e43c.png)

**Comment by avanishsubbiah** [comment]
Well the color_mappings.js supports different color mappings for dark and light themes already. I've just been keeping them the same for convenience.

I'll try putting the mappings for v7 in dark, and v8 in light and see how that looks
