### ISSUE TITLE
Extension keeps regular top bar and other extensions enabled on lock screen

### ISSUE THREAD

**Issue by laurinneff** [avanishsubbiah/material-you-theme#26]
This extension keeps the regular top bar and all other extensions enabled when locking the screen. This leads to **private data being leaked** (notification contents, calendar events, data from other extensions), lets anyone change certain settings that can be accessed through the top bar, and it allows for **arbitrary code execution** (Alt+F2, then type `lg` to access GNOME Shell's debugging tools which have a REPL. Sometimes you need to enter the activities overview first). This is a **serious vulnerability** and should be fixed ASAP. Until then, I recommend that all users of this extension disable it temporarily.

Edit: as an example, here's some code you can enter in the REPL to print your /etc/os-release: `imports.gi.Gio.File.new_for_uri('file:///etc/os-release').load_contents(null)`

Edit 2: I also just found some code you can enter to **completely bypass the lock screen**: `Main.screenShield.deactivate()`

**Comment by workonfire** [comment]
Yeah, I also just stumbled upon this. Here's my screenshot.
![image](https://user-images.githubusercontent.com/34654573/183253301-2c48b66a-1af0-446c-a8b1-e193cf664091.png)

**Comment by avanishsubbiah** [comment]
Hello, I think maybe the extension applying and removing the theme on disable() and enable() might be causing this. This is my first extension, so if anyone has any ideas on what might be causing this feel free to add here or submit pr.

Thanks!

**Comment by avanishsubbiah** [comment]
I disabled notifications in 4e62021. This seems to have fixed the lock screen but definitely needs more testing. Let me know if the issue is reproducible on the new commit.

**Comment by laurinneff** [comment]
Thanks, that solves it. And since that was the solution, I looked into it a bit more and it looks like the underlying bug is in gnome-shell, so I opened an issue over there: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5719
