### ISSUE TITLE
Legacy window decorations don't change

### ISSUE THREAD

**Issue by mikecharles** [avanishsubbiah/material-you-theme#37]
I followed the instructions for legacy window decorations (installed and applied adw-gtk3), but the window decorations for legacy applications remain light blue no matter what color the native libadwaita windows are

#### Native with brown wallpaper

![Screenshot from 2022-08-13 09-33-20](https://user-images.githubusercontent.com/265620/184496743-5cf1d383-f4c7-4af8-947f-40e615e277a7.png)

#### Legacy window with brown wallpaper

![Screenshot from 2022-08-13 09-19-53](https://user-images.githubusercontent.com/265620/184496768-f42d6a94-63f0-4609-9023-f2d33291bed5.png)

#### System info

```
$ uname -a
Linux fedora-linux 5.18.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 3 15:44:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Gnome 42.3 on Wayland

**Comment by FilipeTorresBR** [comment]
The extension User-themes is enabled?
https://extensions.gnome.org/extension/19/user-themes/

**Comment by mikecharles** [comment]
> The extension User-themes is enabled?

Yep

**Comment by alazkaaa** [comment]
GNOME Software already using libadwaita and gtk4.
(Mine on HighContrast theme, only firefox and gnome-tweaks are changed here)
Try to reopen the GNOME Software ig?
![Screenshot from 2022-08-15 16-07-36](https://user-images.githubusercontent.com/89382291/184609019-93ef1166-3f30-41ed-bf12-1619f78939d0.png)

**Comment by mikecharles** [comment]
Thanks, seems to have been a bug that resolved itself after I rebooted. Since I can't reliably reproduce it I will close. Thanks again!
