### ISSUE TITLE
Install Sass with npm button doesn't do anything

### ISSUE THREAD

**Issue by Giggigx** [avanishsubbiah/material-you-theme#40]
The install button on the "install Sass with npm" is broken on my build, I can't get it to do anything at all, I also tried to install sass through npm manually but it doesn't get recognized.
I'm running nodejs 18.7.0-1 and npm 8.17.0-1 on Arch Linux.

**Comment by shiipou** [comment]
Did you used `nvm` to install your `npm` and `nodejs` ?

**Comment by sidevesh** [comment]
I facing this issue too, and I have installed usiong nvm, is that unsupported ?

**Comment by avanishsubbiah** [comment]
The install sass with npm button simply runs the command `npm install --prefix /path/to/extension/folder`. I think that command should still work when npm and nodejs are installed using nvm but I have only tested it with node and npm installed through the distro repos.

**Comment by avanishsubbiah** [comment]
Also, just to be sure. The previous version of the extension just didn't provide any feedback that Sass was installed but the button was working properly in the background. I've updated the extension to change the button label and only show the install button when opening the settings menu if sass isn't already present with commit [828c4fe](https://github.com/avanishsubbiah/material-you-theme/commit/828c4feeede44eaaafa5cadb62644368d63feccf)

**Comment by sidevesh** [comment]
With nodejs and npm installed from apt directly, it does start to work again.
Its fine since in shells nvm still overrodes the apt installed nodejs but this does cause an unnecessary install of nodejs and npm and a bunch of packages that come along side those.

**Comment by sidevesh** [comment]
@avanishsubbiah But even though its working now, I still see the install button.

**Comment by sidevesh** [comment]
that makes sense, I think this can be closed then if @Giggigx also faced this issue due to nvm,
also I think #34 would help solve this too since then nodejs and npm wont be needed if I understand it correctly.

**Comment by Giggigx** [comment]
The problem is that nodejs and npm are installed from the official repository in arch, I don't know why npm from pacman doesn't work.

**Comment by sidevesh** [comment]
npm and nodejs from pacman did work for me on arch.

**Comment by Giggigx** [comment]
I don't know if I'm doing something wrong then, I recorded a video of my issue [here](https://streamable.com/k3pp1l) showing that both npm and nodejs are indeed in my installed packages list in pacman, but the install button doesn't do anything. 
From what i've read i should be able to manually install it by executing `npm install --prefix /path/to/extension sass` right?

**Comment by sidevesh** [comment]
I think running `npm install` from the extension directory is something I had done on ubuntu and it had worked,
you can try that too.
Also, check if `node_modules` shows up or not after clicking Install in the extension directory.

**Comment by avanishsubbiah** [comment]
I think you're running the extension from the extensions store. That version has an unresponsive install button that doesn't tell you if it's working if not. The only way to tell is to see if `node_modules` is in the extension directory. Cloning the git repository to install the newest version makes the install button responsive.

**Comment by Giggigx** [comment]
Turns out that the button was actually working all along, and that made me realize that there is another problem, as soon as I refresh the theme an error about the shell theme could not be applied automatically, what's up with that?
![Screenshot from 2022-08-19 13-35-06](https://user-images.githubusercontent.com/38881699/185610938-a936a9d4-7568-44bd-b925-6f2ca6a712d4.png)
,

**Comment by CosmicFusion** [comment]
> Turns out that the button was actually working all along, and that made me realize that there is another problem, as soon as I refresh the theme an error about the shell theme could not be applied automatically, what's up with that? ![Screenshot from 2022-08-19 13-35-06](https://user-images.githubusercontent.com/38881699/185610938-a936a9d4-7568-44bd-b925-6f2ca6a712d4.png)

same issue

**Comment by avanishsubbiah** [comment]
> Turns out that the button was actually working all along, and that made me realize that there is another problem, as soon as I refresh the theme an error about the shell theme could not be applied automatically, what's up with that? ![Screenshot from 2022-08-19 13-35-06](https://user-images.githubusercontent.com/38881699/185610938-a936a9d4-7568-44bd-b925-6f2ca6a712d4.png)

I should have made the notification a bit more clear. This is just an issue where if you have the "User Themes" extension installed through the extensions store rather than through your distro's repository then the global gsetting `org.gnome.shell.extensions.user-theme` isn't available so the extension cannot set the shell theme to `MaterialYou` automatically. It still generates the theme, you just need to go into Gnome Tweaks and manually set the shell theme to `MaterialYou` (Or if it was already on `MaterialYou` set it to default and then back to `MaterialYou` to have it update with the new changes)

**Comment by Giggigx** [comment]
Thank you for this, it works perfectly now!
I would suggest you to write a paragraph or two about the shell theme on the readme.md file, so that other folks that encounter this problem will have an answer immediately instead of browsing through the issues.
Thank you so much for creating this awesome extension and have a great day!
