### ISSUE TITLE
With some backgrounds the gnome's overview background and the default libadwaita background are the same

### ISSUE THREAD

**Issue by Py-GNU-Unix** [avanishsubbiah/material-you-theme#43]
With some backgrounds the gnome's overview background and the default libadwaita background are the same.

![Screenshot from 2022-08-22 17-46-07](https://user-images.githubusercontent.com/78305798/185964514-0a7f2489-3af4-4eb8-9a78-3a1d352ce5fb.png)
Maybe the extension could check if these two colors are too similar and, in this case, make the overview background or libadwaita backround a bit darker or lighter.

P.S. this extension is awesome !

**Comment by avanishsubbiah** [comment]
Ah, just realized why the scss color definitions file darkened the background color by 15%. I just removed that when I was making the template color definitions file so I'll add that back in in the next release.

**Comment by avanishsubbiah** [comment]
![image](https://user-images.githubusercontent.com/40191253/186289625-1e60584c-917a-4d60-8ee6-f3fd9f438e78.png)

I darkened and desaturated the shell background by 2% which fixes the issue of both window and shell backgrounds being the same color.
