### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by suhail-c** [avanishsubbiah/material-you-theme#45]
mkdir -p material-you-theme@asubbiah.com/po
xgettext --from-code=UTF-8 \
	material-you-theme@asubbiah.com/extension.js \
	-o material-you-theme@asubbiah.com/po/material-you-theme.pot
make: xgettext: No such file or directory
make: *** [Makefile:25: pot] Error 127

**Comment by avanishsubbiah** [comment]
I need to update the readme, installing with make requires the package `gettext`
