### ISSUE TITLE
Theme doesn't apply to adw-gtk3 apps.

### ISSUE THREAD

**Issue by peaprog** [avanishsubbiah/material-you-theme#49]
I have been running Arch Linux with Gnome for a while now. I have the default theme and the adw-gtk3 theme to make it all cohesive. However, the Material You color is only applied to my settings app! No gtk3 apps at all! Is there something I am doing wrong, or is this a bug? (I have all the requirements installed, so I don't see why it wouldn't work) As a Android 13 user now, I would really like my desktop to match my smart phone.

**Comment by ardjuh** [comment]
For native gtk3 apps it should work out of the box (if you have adw-gtk3 theme installed) but it doesn't work for flathub apps out of the box.
Have you installed flatseal and added the correct permissions as stated in the README?

**Comment by peaprog** [comment]
I do use the adw-gtk3 theme. All my apps are from the Arch repositories and the AUR, I don't use FlatPack at all. Could it be an issue I am using the adw-gtk3 dark-theme?

**Comment by ardjuh** [comment]
I use the adw-gtk3-dark theme myself, which works perfectly for me. I'm sorry to hear it doesn't work for you, but I'm afraid I can't help you further because I don't have enough information or time. If you have the latest official version of adw-gtk3 theme installed it just should work. I hope you can fix it!

**Comment by peaprog** [comment]
Alright thanks for your time. I understand you are a very busy person. I'll do some digging and try to fix it. Thanks again, and thanks for creating an awesome theme :D

**Comment by peaprog** [comment]
**Solution:**

Yay did not think that adw-gtk3 was installed. Force un-installing it and re-installing it fixed the issue.
