### ISSUE TITLE
Inconsistency in vibrant color profile between light and dark variants for gtk3 apps

### ISSUE THREAD

**Issue by Neutrovertido** [avanishsubbiah/material-you-theme#50]
As the title implies, there's some inconsistency in the vibrant color profile when using `adw-gtk3-dark` as opposed to `adw-gtk3` theme for gtk3 apps, notably in the context menus.

When using the light variant:
![image](https://user-images.githubusercontent.com/61665012/187811534-6b5fa4b2-ab14-43f0-8e1d-dee93f6f3a57.png)

When using the dark variant:
![image](https://user-images.githubusercontent.com/61665012/187811555-0919a2cc-c14c-4b1a-ae8f-a0a57e7a22ef.png)

Also note that gtk4 apps are exempt from it:
![image](https://user-images.githubusercontent.com/61665012/187811724-510da88a-78aa-48f7-b2f6-a667f3cde448.png)

This only ever happens when using the vibrant color profile, the other profiles do not present this behavior.

So if possible, `adw-gtk3-dark` should also highlight in white instead of the dark alternative color for consistency with gtk4 and just overall a better looking experience.

**Comment by ardjuh** [comment]
For me it highlights in white, is this issue already resolved?
![image](https://user-images.githubusercontent.com/63558466/190710884-cb1cb218-8014-45a6-ae08-1fbb983341a9.png)

**Comment by Neutrovertido** [comment]
> For me it highlights in white, is this issue already resolved?
> ![image](https://user-images.githubusercontent.com/63558466/190710884-cb1cb218-8014-45a6-ae08-1fbb983341a9.png)
> 

Just to make sure, are you using the **vibrant** color profile?
Also log out and log back in to see the whole GTK stylesheet update when switching if not, just in case

**Comment by ardjuh** [comment]
Ah good point, I have the same problem now, gonna take a look at it!

**Comment by Neutrovertido** [comment]
yup, just tried building your fork and works like a charm
