### ISSUE TITLE
MaterialYou shell theme not being generated

### ISSUE THREAD

**Issue by IOplus** [avanishsubbiah/material-you-theme#59]
I have npm, node and sass installed, the dependencies are all good, and I installed the User Themes extension through my distro's repository (Fedora 36). Still, when I try to use the extension I get this notification:

![Screenshot from 2022-09-23 20-24-57](https://user-images.githubusercontent.com/83154700/192072893-e92bbe7f-71b0-4cb6-bc99-6f7252372b92.png)

But it's okay, as seen in [this comment](https://github.com/avanishsubbiah/material-you-theme/issues/40#issuecomment-1221416764), I just need to manually change it from the Gnome Tweaks app.

![Screenshot from 2022-09-23 20-51-33](https://user-images.githubusercontent.com/83154700/192073084-a92bb30c-07ea-4339-923d-1f68167cb4a4.png)

But there is no MaterialYou shell theme installed. I've tried logging out and restarting multiple times.

**Comment by ardjuh** [comment]
Is there something in `~/.local/themes/`?
That's where the generated shell theme should be stored.

**Comment by IOplus** [comment]
> Is there something in `~/.local/themes/`?
> That's where the generated shell theme should be stored.

That directory doesn't even exist in my computer, just tried creating it and reactivating the extension. Still have the same notification and the directory is empty...

**Comment by IOplus** [comment]
> Is there something in `~/.local/themes/`?
> 
> That's where the generated shell theme should be stored.

Okay, I've made some advancements. I created the directory `~/.local/share/themes` and then tried to use the extension, and it created a folder 'MaterialYou' in that directory. But the folder is practically empty, there's only a 'gnome-shell' folder in it, which is empty.

**Comment by Dio-Off-Brando** [comment]
I have the exact same issue, and I did the exact same thing, and the extension crashed.
```
The settings of extension material-you-theme@asubbiah.com had an error:
TypeError: ext_utils.check_npm is not a function

Stack trace:
fillPreferencesWindow@/usr/share/gnome-shell/extensions/material-you-theme@asubbiah.com/prefs.js:206:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by IOplus** [comment]
I found this running `journalctl /usr/bin/gnome-shell -f -o cat`:
```
JS ERROR: ReferenceError: loop is not defined
compile_sass/<@/home/Fedora/issa20omais/.local/share/gnome-shell/extensions/material-you-theme@asubbiah.com/extension.js:345:17

Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.config/gtk-4.0: File exists
Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.config/gtk-3.0: File exists
Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.local/share/themes/MaterialYou: File exists
Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.local/share/themes/MaterialYou/gnome-shell: File exists
JS ERROR: ReferenceError: loop is not defined
compile_sass/<@/home/Fedora/issa20omais/.local/share/gnome-shell/extensions/material-you-theme@asubbiah.com/extension.js:345:17

Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.config/gtk-4.0: File exists
Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.config/gtk-3.0: File exists
```

**Comment by IOplus** [comment]
> Maybe it works if we empty the folders if they exist, but I'm very busy at the moment, so if someone has some free time, it shouldn't be very difficult.

I've already tried emptying/deleting the folders, but then I get this error:

```
JS ERROR: ReferenceError: loop is not defined
compile_sass/<@/home/Fedora/issa20omais/.local/share/gnome-shell/extensions/material-you-theme@asubbiah.com/extension.js:345:17

Gio.IOErrorEnum: Error creating directory /home/Fedora/issa20omais/.config/gtk-4.0: File exists
JS ERROR: GLib.FileError: Failed to open file “/home/Fedora/issa20omais/.config/gtk-3.0/bookmarks”: No such file or directory
```

**Comment by ardjuh** [comment]
Did you empty them by hand or with code?
If you did it by code, can you link the code then.

**Comment by IOplus** [comment]
> Did you empty them by hand or with code? If you did it by code, can you link the code then.

I just ran: `mv ~/.config/gtk-4.0 ~/.config/gtk-4.0.old && mv ~/.config/gtk-3.0 ~/.config/gtk-3.0.old && rm -rf ~/.local/share/themes/MaterialYou`
And then I made sure the folders didn't exist by trying to cd into them

**Comment by Dio-Off-Brando** [comment]
I install it with the AUR package

**Comment by ardjuh** [comment]
I just fixed the loop bug. I don't know why these files cause problems (I don't think this bug fix is going to fix it). Can you try removing the files completely and then enabling this extension?

**Comment by everyx** [comment]
> I just fixed the loop bug. I don't know why these files cause problems (I don't think this bug fix is going to fix it). Can you try removing the files completely and then enabling this extension?

After reinstall from Gnome extension website, It's get work, but there are still some error messages in the log

```js
Gio.IOErrorEnum: 创建目录 /home/everyx/.local/share/themes/MaterialYou 时出错：文件已存在
Gio.IOErrorEnum: 创建目录 /home/everyx/.local/share/themes/MaterialYou/gnome-shell 时出错：文件已存在
Gio.IOErrorEnum: 创建目录 /home/everyx/.config/gtk-4.0 时出错：文件已存在
Gio.IOErrorEnum: 创建目录 /home/everyx/.config/gtk-3.0 时出错：文件已存在
loading user theme: /home/everyx/.local/share/themes/MaterialYou/gnome-shell/gnome-shell.css
loading user theme: /home/everyx/.local/share/themes/MaterialYou/gnome-shell/gnome-shell.css
JS ERROR: ReferenceError: loop is not defined
compile_sass/<@/home/everyx/.local/share/gnome-shell/extensions/material-you-theme@asubbiah.com/extension.js:345:17
```
