### ISSUE TITLE
Bad contrast between colors in right click menus

### ISSUE THREAD

**Issue by peaprog** [avanishsubbiah/material-you-theme#60]
No matter my wallpaper, when the extension mode is set to "vibrant" the right click pop up menus have very bad contrast when you hover the cursor over them. It would be nice to manually augment the theme if necessary, if the contrast issue was fixed, or if the theme could be exported as a .json to edit in Gradience. 

![Snímek obrazovky pořízený 2022-09-24 07-20-20](https://user-images.githubusercontent.com/65086003/192103158-e75b4e90-f8e1-4c0d-9024-2a68b14e70ae.png)

**Comment by ardjuh** [comment]
Duplicate of #50, generating a json file to open in gradience is a good idea though!

**Comment by peaprog** [comment]
Sounds good, thanks for the info!
