### ISSUE TITLE
Theme randomly switches to blue

### ISSUE THREAD

**Issue by peaprog** [avanishsubbiah/material-you-theme#67]
I have the latest version of the extension from https://extensions.gnome.org/ from Gnome 43 and occasionally, when I wake my computer from sleep, the extension will rewrite the previous color pallet with a blue material you theme. Seems to happen fairly randomly. Switching the extension's color modes back and forth fixes the issue temporarily. Maybe add a way to lock the current pallet?

**Comment by ardjuh** [comment]
Yeah I have the same issue since last week or smth. I think it's best to add a option to disable automatic reaplying.

**Comment by ardjuh** [comment]
I think it's a bug in gnome (it also always forgets which wallpaper I chose in the appearance tab)

**Comment by peaprog** [comment]
That makes sense. It stopped doing it earlier this week after I updated my system.
