### ISSUE TITLE
Can't uninstall, add how to

### ISSUE THREAD

**Issue by ginwsby** [avanishsubbiah/material-you-theme#68]
Hi, I tried to remove the extension from the Extensions app, but nothing happens. If I reboot the extension is still there. This is very annoying because even if the extension is disabled, every time I log in I get the notification of the possible update.
How can I completely remove this extension?
Thank you.

**Comment by ardjuh** [comment]
I don't think this is the fault of our extension, but you can go to `~/.local/share/gnome-shell/extensions` and remove the `material-you-theme@assubiah.com` directory.

**Comment by ginwsby** [comment]
Thanks, that solve my problem. 
I don't know why but this is the only extension i can't remove from the extensions app.
