### ISSUE TITLE
The extension doesn't see if it's light / dark dynamic wallpaper, always light.

### ISSUE THREAD

**Issue by darkblaze69** [avanishsubbiah/material-you-theme#7]
Considering default GNOME dynamic light/dark wallpapers like adwaita, truchet, etc. It always gets the color from the light variant, even if extension is set to "Dark mode". 
In dark mode it gets truchet-l.jpg instead of truchet-d.jpg (warm colors instead of cold colors).

**Comment by avanishsubbiah** [comment]
Commit e4ff122 updates the apply_theme() function to pick the light or dark variant of the current wallpaper based on if Dark Mode is toggled on or off.
