### ISSUE TITLE
adjust the contrast on header bars

### ISSUE THREAD

**Issue by allaeddineomc** [avanishsubbiah/material-you-theme#9]
the contrast on header bar toggles is low 
![Screenshot from 2022-08-03 00-18-42](https://user-images.githubusercontent.com/57415185/182492620-009db4bc-4f41-4fb2-9da0-8a9f28ba9eec.png)
![Screenshot from 2022-08-03 00-18-55](https://user-images.githubusercontent.com/57415185/182492624-864f36a3-024d-4a6b-b74b-df944f5d4848.png)

like in this screenshot here , the toggle is almost invisible 

i think the best way to do it will be making the toggle brighter on dark theme and darker on light , also making the header bar a bit darker on the dark theme will be a nice improvement

**Comment by avanishsubbiah** [comment]
Fixed with f10b256 by changing `accent_bg_color` to use material token `primary` instead of `primaryContainer`
